name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ritiklrt2/evoque-be:latest .

      - name: Docker push image
        run: docker push ritiklrt2/evoque-be:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Pull and build docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Login to Docker Hub (or your registry)
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
            docker pull ritiklrt2/evoque-be:latest
            docker stop evoque-be || true
            docker rm evoque-be || true
            docker run -d -p 3006:8000 --name evoque-be ritiklrt2/evoque-be:latest
